In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

## TODO: Replace with the path to your dataset
PATH_TO_DATASET = 'complaints.csv' 
############################################################

data = pd.read_csv(PATH_TO_DATASET)
data.head()

C:\Users\zenan\AppData\Local\Temp\ipykernel_6076\2905885950.py:10: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(PATH_TO_DATASET)


Date received                                            Product  \
0    2023-01-31                                           Mortgage   
1    2023-04-10  Credit reporting, credit repair services, or o...   
2    2023-04-09  Credit reporting, credit repair services, or o...   
3    2023-04-08  Credit reporting, credit repair services, or o...   
4    2022-03-10  Credit reporting, credit repair services, or o...   

                  Sub-product  \
0  Conventional home mortgage   
1            Credit reporting   
2            Credit reporting   
3            Credit reporting   
4            Credit reporting   

                                               Issue  \
0                     Trouble during payment process   
1                        Improper use of your report   
2  Problem with a credit reporting company's inve...   
3  Problem with a credit reporting company's inve...   
4               Incorrect information on your report   

                                           Sub-issue  \
0                                                NaN   
1  Credit inquiries on your report that you don't...   
2               Investigation took more than 30 days   
3               Investigation took more than 30 days   
4                           Account status incorrect   

                        Consumer complaint narrative  \
0  I purchased and financed my home through wells...   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                             Company public response  \
0  Company has responded to the consumer and the ...   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                               Company State ZIP code           Tags  \
0                WELLS FARGO & COMPANY    OR  97048.0  Servicemember   
1             AMERICAN EXPRESS COMPANY    IN  46815.0            NaN   
2  Experian Information Solutions Inc.    CA  95210.0            NaN   
3  Experian Information Solutions Inc.    AZ  85381.0            NaN   
4                        DISCOVER BANK    DE  19703.0            NaN   

  Consumer consent provided? Submitted via Date sent to company  \
0           Consent provided           Web           2023-01-31   
1                        NaN           Web           2023-04-10   
2                        NaN           Web           2023-04-09   
3                        NaN           Web           2023-04-08   
4                        NaN      Referral           2022-03-11   

      Company response to consumer Timely response? Consumer disputed?  \
0      Closed with monetary relief              Yes                NaN   
1  Closed with non-monetary relief              Yes                NaN   
2                      In progress              Yes                NaN   
3                      In progress              Yes                NaN   
4      Closed with monetary relief              Yes                NaN   

   Complaint ID  
0       6510170  
1       6819440  
2       6812250  
3       6811608  
4       5318105

## We are selecting a random sample of x rows

In [2]:
x = 1000
df = data.sample(n=x, random_state=42)

In [3]:
# Reset index for the sample, for the original data we may not need to do this
df.reset_index(drop=True, inplace=True)
df.head

<bound method NDFrame.head of     Date received                                            Product  \
0      2021-04-19                                           Mortgage   
1      2020-04-29  Credit reporting, credit repair services, or o...   
2      2015-08-14                                    Debt collection   
3      2020-08-18                        Credit card or prepaid card   
4      2021-02-13                        Credit card or prepaid card   
..            ...                                                ...   
995    2014-09-04                                    Debt collection   
996    2022-08-15  Credit reporting, credit repair services, or o...   
997    2017-07-26                        Checking or savings account   
998    2017-01-23                                       Student loan   
999    2018-04-27                                    Debt collection   

                                    Sub-product  \
0                                  FHA mortgage   
1  

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df=df.fillna('')
df['combined_text'] = df['Product'] + ' ' + df['Sub-product'] + ' ' + df['Issue'] + ' ' + df['Sub-issue'] + ' ' + df['Consumer complaint narrative'] + ' ' + df['Company public response'] + ' ' + df['Company'] + ' ' + df['Company response to consumer']
df['combined_text']

0      Mortgage FHA mortgage Struggling to pay mortga...
1      Credit reporting, credit repair services, or o...
2      Debt collection Medical Cont'd attempts collec...
3      Credit card or prepaid card Store credit card ...
4      Credit card or prepaid card General-purpose cr...
                             ...                        
995    Debt collection I do not know Cont'd attempts ...
996    Credit reporting, credit repair services, or o...
997    Checking or savings account Other banking prod...
998    Student loan Federal student loan servicing Ca...
999    Debt collection Other debt Took or threatened ...
Name: combined_text, Length: 1000, dtype: object

In [5]:
vectorizer = TfidfVectorizer(stop_words='english')
vectors = vectorizer.fit_transform(df['combined_text'])

# Calculate cosine similarity
similarities = cosine_similarity(vectors)

In [6]:
print(similarities)

[[1.         0.01340071 0.00747798 ... 0.00683866 0.11571362 0.00108787]
 [0.01340071 1.         0.01624795 ... 0.04158255 0.00451727 0.00843917]
 [0.00747798 0.01624795 1.         ... 0.00829166 0.00252077 0.04026484]
 ...
 [0.00683866 0.04158255 0.00829166 ... 1.         0.00230525 0.0365015 ]
 [0.11571362 0.00451727 0.00252077 ... 0.00230525 1.         0.07909993]
 [0.00108787 0.00843917 0.04026484 ... 0.0365015  0.07909993 1.        ]]


In [7]:
# Identify duplicate rows
duplicates = []
for i in range(similarities.shape[0]):
    for j in range(i+1, similarities.shape[0]):
        if similarities[i, j] > 0.9:   # Define a threshold for similarity
            duplicates.append((i, j))

In [8]:
print(duplicates)

[(1, 130), (1, 131), (1, 205), (1, 446), (1, 561), (1, 621), (1, 710), (1, 804), (1, 878), (1, 950), (1, 982), (6, 360), (6, 410), (6, 812), (7, 28), (7, 61), (7, 113), (7, 175), (7, 230), (7, 248), (7, 250), (7, 345), (7, 390), (7, 433), (7, 452), (7, 502), (7, 549), (7, 595), (7, 617), (7, 622), (7, 640), (7, 645), (7, 683), (7, 707), (7, 721), (7, 783), (7, 785), (7, 795), (7, 854), (7, 867), (7, 903), (7, 924), (7, 946), (7, 980), (7, 987), (8, 380), (8, 574), (9, 19), (9, 25), (9, 39), (9, 105), (9, 134), (9, 165), (9, 194), (9, 197), (9, 207), (9, 208), (9, 213), (9, 238), (9, 282), (9, 305), (9, 350), (9, 363), (9, 376), (9, 383), (9, 432), (9, 441), (9, 444), (9, 462), (9, 479), (9, 518), (9, 547), (9, 550), (9, 553), (9, 567), (9, 568), (9, 673), (9, 681), (9, 704), (9, 730), (9, 791), (9, 847), (9, 880), (9, 931), (9, 973), (9, 993), (10, 814), (11, 53), (11, 137), (11, 156), (11, 223), (11, 563), (11, 779), (11, 868), (14, 149), (14, 589), (14, 623), (14, 728), (14, 947), (1

In [9]:
print("Number of duplicate pairs:", len(duplicates))

Number of duplicate pairs: 2549


In [10]:
# Remove duplicate rows
df.drop(index=[dup[1] for dup in duplicates], inplace=True)

In [11]:
# Reset the index
df.reset_index(drop=True, inplace=True)

In [12]:
df

Date received                                            Product  \
0      2021-04-19                                           Mortgage   
1      2020-04-29  Credit reporting, credit repair services, or o...   
2      2015-08-14                                    Debt collection   
3      2020-08-18                        Credit card or prepaid card   
4      2021-02-13                        Credit card or prepaid card   
..            ...                                                ...   
696    2023-01-06                                    Debt collection   
697    2014-09-04                                    Debt collection   
698    2017-07-26                        Checking or savings account   
699    2017-01-23                                       Student loan   
700    2018-04-27                                    Debt collection   

                                    Sub-product  \
0                                  FHA mortgage   
1                              Credit reporting   
2                                       Medical   
3                             Store credit card   
4    General-purpose credit card or charge card   
..                                          ...   
696                                  Other debt   
697                               I do not know   
698            Other banking product or service   
699              Federal student loan servicing   
700                                  Other debt   

                                                 Issue  \
0                           Struggling to pay mortgage   
1                 Incorrect information on your report   
2                Cont'd attempts collect debt not owed   
3      Problem with a purchase shown on your statement   
4                   Other features, terms, or problems   
..                                                 ...   
696                    Written notification about debt   
697              Cont'd attempts collect debt not owed   
698             Problem caused by your funds being low   
699                                Can't repay my loan   
700  Took or threatened to take negative or legal a...   

                                             Sub-issue  \
0                                                        
1                             Account status incorrect   
2                                        Debt was paid   
3    Credit card company isn't resolving a dispute ...   
4                                        Other problem   
..                                                 ...   
696   Didn't receive enough information to verify debt   
697                                   Debt is not mine   
698                      Overdrafts and overdraft fees   
699                 Can't decrease my monthly payments   
700     Collected or attempted to collect exempt funds   

                          Consumer complaint narrative  \
0                                                        
1                                                        
2                                                        
3    I purchased 4 utility vest from XXXX XXXX on X...   
4                                                        
..                                                 ...   
696                                                      
697                                                      
698                                                      
699  Requested to have my school loan income lowere...   
700  Received Workers ' Compensation Via Workers ' ...   

                               Company public response  \
0                                                        
1                                                        
2                                                        
3                                                        
4                                                        
..                                                 ...   
696  Company has responded to

## The sample runs successfully, but for the original df it takes too long to run. We will try finding another method meanwhile.

In [ ]:
# until

print(df.isnull().sum())

In [ ]:
df['Timely response?'].value_counts().plot(kind='bar')

In [ ]:
plt.figure(figsize=(20, 20))
df['State'].value_counts().plot(kind='bar')

In [ ]:
plt.figure(figsize=(20, 20))
df['Issue'].value_counts()[:20].plot(kind='bar')

In [ ]:
df['Company'].value_counts()[:20].plot(kind='bar')

In [ ]:
df.info()

In [ ]:
print(df.isnull().sum())

235163/2573063 = 9.1%
653711/2573063 =64%
sub-issue, Consumer complaint narrative，Company public response, Tags, Consumer disputed? need to drop
Sub-product, State，ZIP code missing value can be replaced by mode

In [ ]:
df = df.drop(['Sub-product', 'Consumer complaint narrative','Company public response','Tags','Consumer disputed?','Consumer consent provided?'], axis=1)


In [ ]:

df['State'].fillna(df['State'].mode()[0])
df['ZIP code'].fillna(df['ZIP code'].mode()[0])

In [ ]:
counts2 = df['State'].value_counts().to_dict()
print(counts2)

In [ ]:
df['State']= df['State'].fillna('CA')

In [ ]:
counts3 = df['ZIP code'].value_counts().to_dict()
print(counts3)

In [ ]:
df['ZIP code']= df['ZIP code'].fillna('30349.0')

In [ ]:
df.head()

In [ ]:
df.tail()